# config.yaml
experiment: wind_transformer_diffusion

model:
  input_dim: 7
  model_dim: 256
  seq_len: 48
  timesteps: 200
  num_layers: 6
  dropout: 0.1   # 新增这一行

training:
  batch_size: 64
  epochs: 100
  lr: 1e-4
  optimizer: adamw

loss:
  type: mse
  # type: mae

sample:
  n_samples: 1000
  save_path: "samples/"
